apiVersion: v1
kind: ConfigMap
metadata:
  name: aws-cli-config
  namespace: {{ .Release.Namespace }}
data:
  config: |
    [default]
    region = {{ .Values.aws.region }}
    output = {{ .Values.aws.output }}